# Generated by Django 4.1.5 on 2023-01-14 07:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('divulgar', '0002_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foto', models.ImageField(upload_to='fotos_pets', verbose_name='Foto')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
                ('descricao', models.TextField(verbose_name='Descrição')),
                ('estado', models.CharField(max_length=50, verbose_name='UF')),
                ('cidade', models.CharField(max_length=50, verbose_name='Cidade')),
                ('telefone', models.CharField(max_length=14, verbose_name='Telefone')),
                ('status', models.CharField(choices=[('P', 'Para Adoção'), ('A', 'Adotado')], max_length=1, verbose_name='Status')),
                ('raca', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='divulgar.raca', verbose_name='Raça')),
                ('tags', models.ManyToManyField(to='divulgar.tag', verbose_name='Tag')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
            options={
                'verbose_name': 'Pet',
                'verbose_name_plural': 'Pets',
                'db_table': 'Pet',
                'ordering': ['nome', 'raca'],
            },
        ),
    ]
